openapi : 3.0.0

info:
     title: Tshirt Ecomm shop
     description: Express using node js
     version: 1.0.0
     contact:
       email : sundar@google.com
       url : "https://github.com/Sundarleo11"
     
servers: 
- url: "{protocol}://localhost:5000/api/{version}"
  description: Development server for local Host
  variables:
   version:
    enum:
     - v1
     - v2
    default: v1
   protocol:
    enum:
    - http
    - https
    default: http

components:
 securitySchemes:

   ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

   BearerAuth:
      type: http
      scheme: bearer 


paths:
  /:
    get:
     tags:
      - String
     summary: Home
     responses: 
      200:
        description: All good success
        content:
          application/json:
           schema:
            type: string
            example : "mystring"

      400:
        description: Bad request
      500:      
        description: internal server error